In [1]:
pip install sentence-transformers

Note: you may need to restart the kernel to use updated packages.


In [2]:
from sentence_transformers import SentenceTransformer

In [3]:
model = SentenceTransformer('distilbert-base-nli-stsb-mean-tokens')

In [4]:
model.encode("This is Maheswara Reddy")

array([ 9.26344931e-01,  7.30214536e-01,  4.98026133e-01, -1.01153123e+00,
        2.93824345e-01,  2.52459019e-01,  8.60979438e-01,  1.38714063e+00,
       -6.61041439e-01, -3.04382920e-01, -2.35853523e-01,  3.18501592e-01,
        6.67159736e-01,  1.04768038e+00, -1.52146131e-01, -7.21165597e-01,
       -7.05979824e-01, -2.18993068e-01,  4.94306326e-01,  1.94832921e-01,
        7.02717066e-01, -3.84718001e-01,  2.70935241e-02,  1.02834654e+00,
       -1.11914746e-01,  7.34000683e-01,  4.83846575e-01,  9.36823428e-01,
       -3.55927885e-01, -4.07842815e-01,  9.60192919e-01, -1.11643016e+00,
        4.30828691e-01,  5.79280436e-01, -3.68326843e-01, -4.33676094e-01,
       -4.24106181e-01, -4.02442634e-01, -3.92487496e-01,  3.97669733e-01,
        1.25834644e-01, -9.03876662e-01,  2.26642609e-01, -6.15972996e-01,
        3.77874449e-03,  3.85614514e-01, -6.08562469e-01,  4.82505918e-01,
       -4.51276183e-01, -3.54428947e-01, -4.94504571e-01,  1.99927121e-01,
        3.71159256e-01, -

In [5]:
s1 = "I hate this product"
s2 = "I love this product"

In [6]:
e1 = model.encode(s1).reshape(1,-1)
e2 = model.encode(s2).reshape(1,-1)

In [8]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(e1, e2)

array([[0.22844896]], dtype=float32)

In [9]:
from transformers import DistilBertTokenizer, DistilBertModel
import torch

In [10]:
name = 'distilbert-base-uncased'
tokenizer = DistilBertTokenizer.from_pretrained(name)
model = DistilBertModel.from_pretrained(name)

In [11]:
i_s1 = tokenizer(s1, return_tensors='pt')
i_s2 = tokenizer(s2, return_tensors='pt')

In [12]:
with torch.no_grad():
    o1 = model(**i_s1)
    o2 = model(**i_s2)

In [13]:
e1 = o1.last_hidden_state.mean(dim=1).numpy()
e2 = o2.last_hidden_state.mean(dim=1).numpy()

In [14]:
cosine_similarity(e1, e2)

array([[0.91308236]], dtype=float32)